import "../globals.css";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/providers/ThemeProviders";
import Navbar from "@/components/Navbar";
import { Jost } from "next/font/google";
import Providers from "@/providers/Providers";

const jost = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "Gym App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${jost.variable} `}>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="w-full overflow-hidden ">
              <div className=" w-full fixed top-0 z-50 ">
                <Navbar />
              </div>
              <div className="mt-[70px]  ">{children}</div>
              <Footer />
            </div>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
